### ISSUE TITLE
Issue with dbt-duckdb Plugin Not Being Recognized

### ISSUE THREAD

**Issue by vmonney** [duckdb/dbt-duckdb#177]
**Description**:

I am encountering an issue with the dbt-duckdb plugin. After installing the plugin using `pip install dbt-duckdb`, it does not appear in the list of installed plugins when I run `dbt --version`.

The output of `dbt --version` is as follows:

```
Core:
  - installed: 1.5.0
  - latest:    1.5.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 1.5.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

I believe my `profiles.yml` is correctly configured for the duckdb plugin:

```
pg-dbt-workshop:

  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'nyc_taxi.duckdb'
```

However, when I run `dbt build`, I encounter the following error:

```
23:03:56  Running with dbt=1.5.0
23:03:56  Error importing adapter: No module named 'dbt.adapters.duckdb'
23:03:56  Encountered an error:
Runtime Error
  Credentials in profile "pg-dbt-workshop", target "dev" invalid: Runtime Error
    Could not find adapter type duckdb!
```

Any assistance or guidance on how to resolve this issue would be greatly appreciated.

**Steps to Reproduce**:

1. Run `pip install dbt-duckdb`
2. Run `dbt --version`
3. Notice that the dbt-duckdb plugin is not listed.
4. Run `dbt build`
5. Notice the error indicating that dbt could not find the duckdb adapter.

**Expected Behavior**:

I expect the dbt-duckdb plugin to be listed as an installed plugin after installation, and I expect `dbt build` to run successfully without errors.

**Actual Behavior**:

The dbt-duckdb plugin is not listed as an installed plugin after installation, and `dbt build` returns an error indicating that it could not find the duckdb adapter.

**Environment**:
- dbt version: 1.5.0
- OS: macOS Ventura 13.4 (M1 chip)
- Python version: 3.9.7

**Comment by jwills** [comment]
Try doing the install with pip3 instead of pip; Mac Python environments are notoriously tricky
