### ISSUE TITLE
plugin config not recognized

### ISSUE THREAD

**Issue by mathews** [duckdb/dbt-duckdb#185]
$ dbt --version
Core:
  - installed: 1.5.1
  - latest:    1.5.1 - Up to date!

Plugins:
  - duckdb: 1.5.1 - Could not determine latest version

with profile config as :
  outputs:
    local:
      type: duckdb
      path:  tttttttttt.duckdb
      threads: 20
      plugins:
        # - module: models_func.funcs.dbt_duckdb_plugin.ModelsShopDuckdbUdfPlugin
        - module: gsheet
          config:
            method: oauth

dbt build will throw error:
   02:18:10  Running with dbt=1.5.1
   02:18:10  Encountered an error:
   Runtime Error
     Credentials in profile "models_shop", target "local" invalid: [{'module': 'gsheet', 'config': {'method': 'oauth'}}] is not valid under any of the given schemas

**Comment by mathews** [comment]
the dbt-duckdb package from pypi.org is poisonous, just not working.  after building wheel from the main branch, and installed the wheel, it works.
Thanks quite a lot for such a great work.

**Comment by jwills** [comment]
yeah, sorry about that-- I didn't document the plugin stuff for 1.5.1 because I didn't feel like I had gotten it quite right yet, and the stuff that is in there is pretty half-baked and broken. I'll cut a new release shortly with the latest stuff on master (that sounds like it worked for you?)
