### ISSUE TITLE
Can a new version be released (e.g. 1.6.1)

### ISSUE THREAD

**Issue by l1xnan** [duckdb/dbt-duckdb#266]
Recently some PR is what I need, I don't like to use `pip install git+https` to install packages, can I release a new version (e.g. 1.6.1 or 1.6.1.pre)?

**Comment by jwills** [comment]
Hey there, I will definitely do one this week but I'm trying to get a few more things in to the next release-- can it wait a few more days?

**Comment by l1xnan** [comment]
OK, thank you!
