### ISSUE TITLE
Python models and external materialisation

### ISSUE THREAD

**Issue by Nintorac** [duckdb/dbt-duckdb#300]
Python models do not respect the `external` materialisation flag and fall back to model

**Comment by AlexanderVR** [comment]
Python models have their materialization set to `table` by default. You can override this within the python model definition by setting `dbt.config(materialization="external")`

Unfortunately you can't do the override from yaml, as reported in this bug:
https://github.com/dbt-labs/dbt-core/issues/8520

**Comment by Nintorac** [comment]
oh awesome, thanks!

**Comment by devmessias** [comment]
Hi @AlexanderVR and @Nintorac, I've fixed this bug in this PR https://github.com/dbt-labs/dbt-core/pull/8538, but I think it got lost in the limbo of PRs. Perhaps if more people comment on the PR, the dbt-core team might review it. 

Note: I tested this PR on a  dbt fork for my company and it worked in our pipeline.
