### ISSUE TITLE
pip install on windows 10 fails with error C2485: '__restrict': unrecognized extended attribute

### ISSUE THREAD

**Issue by jp187** [duckdb/dbt-duckdb#319]
Getting failure in pip install dbt-duckdb on windows 10 using VSC 2022 command line build tools.

Error:```

     arena.cpp
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(267): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(269): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(273): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(275): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(279): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/jemalloc.h(281): error C2485: '__restrict': unrecognized extended attribute
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/internal/jemalloc_internal_macros.h(36): warning C4005: 'restrict': macro redefinition
      duckdb_build/extension/jemalloc/jemalloc/include\jemalloc/internal/jemalloc_internal_decls.h(87): note: see previous definition of 'restrict'
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
```

**Comment by jwills** [comment]
Looks like this:
https://github.com/duckdb/duckdb/issues/9301

**Comment by jp187** [comment]
@jwills   Thank you for the quick response!  I missed [duckdb/duckdb#9301](https://github.com/duckdb/duckdb/issues/9301) .  I installed python 3.11 and that addressed the issue.
