### ISSUE TITLE
Bump DuckDB version to 0.10.0

### ISSUE THREAD

**Issue by NatElkins** [duckdb/dbt-duckdb#338]
Hi,

Not entirely sure if my understanding is correct, but DuckDB is bundled with this plugin, is that correct?  If so, does this package need to be rebuilt/released to support DuckDB [0.10.0](https://duckdb.org/2024/02/13/announcing-duckdb-0100.html)?

Thank you!

**Comment by jwills** [comment]
Hey Nat-- no, all we do [here](https://github.com/duckdb/dbt-duckdb/blob/master/setup.py#L41) is specify a minimum DuckDB version (currently 0.7.0); you should be able to use any DuckDB version greater than that with the 1.7.x line of adapters.

I do periodically bump the minimum version the adapter supports (e.g. I will likely bump things to 0.8.0+ pretty soon to clean up some cruft), but I almost always go out of my way to support multiple versions of DuckDB so folks can upgrade at their leisure.
