### ISSUE TITLE
[Question] Spatial extension

### ISSUE THREAD

**Issue by ran-codes** [duckdb/dbt-duckdb#366]
does anyone know if its possible or if theres any exmaples of using the duck db spatial extension in duckdb-dbt?

**Comment by jwills** [comment]
Should work fine; are you running into a problem?

**Comment by ran-codes** [comment]
very new to duckdb and dbt and just wonder before I dive into. Btw do you know of any examples if not. thank you for the clarification!!

**Comment by jwills** [comment]
AFAICT folks do use the two in combination (the spatial extension with dbt-duckdb, e.g. https://github.com/duckdb/duckdb_spatial/issues/256 ) but I don't know of any projects folks have posted as examples, I'm sorry!

**Comment by ran-codes** [comment]
thanks!
