### ISSUE TITLE
persist_docs / (COMMENT ON Statement) support

### ISSUE THREAD

**Issue by bensonchoyintuitas** [duckdb/dbt-duckdb#398]
Hi is there any chance of the adapter supporting the https://docs.getdbt.com/reference/resource-configs/persist_docs capability so that I can leverage that metadata downstream for data governance?

Currently running with persist_docs on results in:

"ERROR: alter_column_comment macro not implemented for adapter duckdb"

**Comment by jwills** [comment]
I added that recently; it should be in anything after dbt-duckdb 1.7.4 and DuckDB 0.10.1 (when all of the COMMENT ON support dbt needed was added)
