### ISSUE TITLE
use of python API create_function

### ISSUE THREAD

**Issue by wj-c** [duckdb/dbt-duckdb#424]
Can I include a python UDF in dbt duckdb sql files as in [https://duckdb.org/docs/api/python/function](url) ?

Thanks!

**Comment by jwills** [comment]
yes, we do using dbt-duckdb plugins! https://github.com/duckdb/dbt-duckdb/tree/master?tab=readme-ov-file#configuring-dbt-duckdb-plugins

**Comment by wj-c** [comment]
> jwills

thank you jwills
