### ISSUE TITLE
Can not open database file

### ISSUE THREAD

**Issue by nasserHHDE** [duckdb/dbt-duckdb#455]
I have a data ingestion code written in python and today morning raised an error as follows:
07-Oct-24 09:28:47 - Exception occurred:
07-Oct-24 09:28:47 - Error: FATAL Error: Failed to create checkpoint because of error: fsync failed!
07-Oct-24 09:28:51 - DB con. closed

I tried to relaunch the program but it throw an exception as:
07-Oct-24 10:48:19 - Exception occurred:
07-Oct-24 10:48:19 - Error: IO Error: No more data remaining in MetadataReader

I tried to open the database file from the **duckdb cli** but also shows same error message.
I am worried if the database file is corrupted, since the filesystem where the file was stored was restarted for urgent maintenance.

How to solve this problem and is there. away to restore or import this data?

**Comment by nasserHHDE** [comment]
Error: unable to open database "/home/alqudami/scratch/fs_db/backup.db": IO Error: No more data remaining in MetadataReader

**Comment by guenp** [comment]
@nasserHHDE is it possible you're running low on disk space? See this issue: https://github.com/duckdb/duckdb/issues/9667

**Comment by nasserHHDE** [comment]
Yes, the filesystem cluster was shutdown for urgent maintenance, but since then the database file is corrupted and couldn't be open anymore. I was wondering if there any tool in duckdb to import/recover the data?

**Comment by guenp** [comment]
@nasserHHDE, sorry I am not sure, I imagine that what happened is that your database file got in a corrupted state because of the filesystem restart and some data got lost. I would follow up in the above issue and see if anyone has advice for you. I'm going to close this issue for now, let us know if you figure out a way to recover your data!
