### ISSUE TITLE
Tolerate `grants` in models

### ISSUE THREAD

**Issue by benjaminbauer** [duckdb/dbt-duckdb#458]
# Use Case
I want to use a duckdb target alongside a postgres target. One challenge: I define [grants](https://docs.getdbt.com/reference/resource-configs/grants) in my `dbt_project.yml`

# Current behaviour
I get a parser error with the duckdb target

# Desired behaviour
The duckdb target works with defined grants and ignores the grants with a warning like `grants defined on x ignored, unsupported by duckdb`

**Comment by jwills** [comment]
Hey @benjaminbauer, thanks for the heads up here-- I _think_ that the change in PR #459 is all that is required here, but I'm wondering if there is any other stuff like this that would be needed for a smooth switch between Postgres and DuckDB for a project? Maybe indexes too (which aren't yet supported in dbt-duckdb for reasons, though I do periodically try to make them work every now and again)

**Comment by benjaminbauer** [comment]
@jwills thanks for the prompt PR!

I am not that far into this journey. The biggest pain by far I have, are missmatches in built in functions, e.g. `to_date` in pg vs `strptime` in duckdb -> big pain but not a dbt-duckdb topic, can be solved with jinja2 and some copium.

I did not stumble over indexes so far, because dbt-duckdb does not fail when indexes are defined in dbt.

Other than that, my models build w/o problems.

A point that _could_ be a pain: [contract](https://docs.getdbt.com/reference/resource-configs/contract) enforcement and the related [constraints](https://docs.getdbt.com/reference/resource-properties/constraints). So far I only do `data_type`, `non_null`, and `unique`. All of which are supported or at least dbt-duckdb did not warn about the lack thereof

**Comment by benjaminbauer** [comment]
the PR works for me btw 🚀 

I get the message `Grants are not (currently!) supported for DuckDB` as expected. Can you make that a warning?

**Comment by jwills** [comment]
yes, easily! I also changed it to include the name of the relation in question, will upgrade from info -> warn in the PR

**Comment by jwills** [comment]
Oops, nope, I lied-- it can only be an `info` apparently: https://docs.getdbt.com/reference/dbt-jinja-functions/log

**Comment by benjaminbauer** [comment]
on second thoughts: that will probably be really noisy, because grants are often used for a whole group of models. Would it be possible to have a global warning if grants are present and not nag on each instance?

**Comment by benjaminbauer** [comment]
if you want to warn, this is the way I assume: https://docs.getdbt.com/reference/dbt-jinja-functions/exceptions#warn

**Comment by benjaminbauer** [comment]
The hypothetical `log_once` (`warn_once`?) would also apply nicely to indexes. For larger dbt projects I`d prefer to be warned once, front and centre, that no (or only some) indexes will be created

**Comment by jwills** [comment]
trying to think of some other such cases that would make it worthwhile for me to write this function 🤔

**Comment by jwills** [comment]
> does the plugin support all [constraints](https://docs.getdbt.com/reference/resource-properties/constraints#defining-constraints) yet?

yes, we support all of them with an asterisk for foreign key stuff: https://github.com/duckdb/dbt-duckdb/issues/425

**Comment by jwills** [comment]
@benjaminbauer would you do me a solid and try out the PR branch again? I added the `warn_once` functionality and while it looks like it should work I would love a real test case for it to ensure it behaves as expected/desired here

**Comment by benjaminbauer** [comment]
lgtm 🙏
