### ISSUE TITLE
[Question] How does dbt-duckdb versioning relate to dbt-core?

### ISSUE THREAD

**Issue by benjaminbauer** [duckdb/dbt-duckdb#461]
If I want to use e.g. dbt-duckdb in v1.9.0

1. It supports dbt-core <=  v1.9.0
2. It supports dbt-core  >=  v1.9.0
3. There is no tested/fixed correlation between dbt-duckdb and dbt-core versioning

Either way, it would be cool to have a README section for this

**Comment by jwills** [comment]
The decoupling of  `dbt-<adapter>` and `dbt-core` is a recent phenomenon, and I suspect we will keep de facto parity with them for awhile. In this case, we cut dbt-duckdb 1.9.0 b/c of a bug from where we had a hidden dependency on a feature in dbt-core 1.8.x that was removed in dbt-core 1.9.0.

**Comment by benjaminbauer** [comment]
So dbt-duckdb 1.x should work with dbt-core <= 1.x?

**Comment by jwills** [comment]
dbt-duckdb 1.x should always work with dbt-core 1.x; the ability of dbt-duckdb 1.9.0 to work with dbt-core 1.8.x is a recent phenomenon where dbt broke out the adapter interface into a separate module (https://github.com/dbt-labs/dbt-adapters ) that is upstream of dbt-core.
