### ISSUE TITLE
Update dbt-duckdb Postgres Plugin to Use New ATTACH Syntax

### ISSUE THREAD

**Issue by Gexar** [duckdb/dbt-duckdb#478]
The current implementation of the dbt-duckdb Postgres plugin utilizes the deprecated CALL postgres_attach syntax to connect to PostgreSQL databases from DuckDB version 0.8. With the release of DuckDB version 0.9, the recommended approach is to use the ATTACH command with the TYPE POSTGRES parameter.

This issue aims to update the Postgres plugin to:
- Replace the deprecated CALL postgres_attach syntax with the new ATTACH command.
- Incorporate new features and configuration options available in the latest version of the DuckDB Postgres extension.
- Update unit tests to reflect the changes.
- Implement appropriate logging using AdapterLogger for better debugging and traceability.
- Restore the write functionality to the connected pgsql db

Upd: added comment about write functionality

**Comment by Gexar** [comment]
@jwills please assign this to me, I will create a PR for the update.

**Comment by jwills** [comment]
Hey, thank you!

**Comment by Gexar** [comment]
Hi @jwills,

could you please comment on the linked pr, should I add/remove something?
