### ISSUE TITLE
A `dict` type hint broke the package for Python 3.8

### ISSUE THREAD

**Issue by georgesittas** [duckdb/dbt-duckdb#488]
Hello 👋 

It looks like [this](https://github.com/duckdb/dbt-duckdb/commit/9f9cdb14762fdd1e002f67bb64847267191ed388) commit introduced a type hint that's incompatible with Python 3.8:

```python
    _temp_schema_model_uuid: dict[str, str] = defaultdict(lambda: str(uuid4()).split("-")[-1])
```

Specifically, it leads to this error: `TypeError: 'type' object is not subscriptable`.

I figured I'd report this because the [PyPI page](https://pypi.org/project/dbt-duckdb/) shows that the minimum required Python version is 3.8; although, interestingly, it's not included in the testing [version matrix](https://github.com/duckdb/dbt-duckdb/blob/master/.github/workflows/main.yml#L68-L76).

Following the existing patterns in the codebase, a fix could look like:

```python
from typing import Dict

...
    _temp_schema_model_uuid: Dict[str, str] = defaultdict(lambda: str(uuid4()).split("-")[-1])
...
```

Thanks in advance.

**Comment by jwills** [comment]
Ahh thanks for the heads up here— I had meant to drop support for 3.8 on the new versions and didn’t realize I hadn’t updated it in the setup.py file, will do that shortly!

**Comment by georgesittas** [comment]
I'll go ahead and close this issue, it seems like the pypi page has been updated as well. Thanks for the quick turnaround!
